ci: tests reporter and test on both os-agents

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,7 +6,8 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
+  build-linux:
+    name: Build & Test (linux)
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -30,14 +31,56 @@ jobs:
     - name: Run Tests
       env:
         DGTP_TESTS_INTEGRATION_CONNECTION: ${{ secrets.DGTP_TESTS_INTEGRATION_CONNECTION }}
-      run: dotnet test /p:CollectCoverage=true --no-build --verbosity normal
+      run: dotnet test /p:CollectCoverage=true --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Windows Tests            
+        path: tests/**/test-results.trx
+        reporter: dotnet-trx
+
+  build-windows:
+    name: Build & Test (windows)
+    runs-on: windows-latest
+    steps:
+    - uses: actions/checkout@v3
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v3
+      with:
+        dotnet-version: 7.0.x
+    - uses: actions/cache@v1
+      with:
+        path: ~/.nuget/packages
+        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
+        restore-keys: |
+          ${{ runner.os }}-nuget-
+    - name: Restore dependencies
+      run: dotnet restore
+    - name: Build
+      run: dotnet build --no-restore
+    - name: Enable Integration Tests
+      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
+      run: echo "DGTP_TESTS_INTEGRATION_RUN=TRUE" >> $GITHUB_ENV
+    - name: Run Tests
+      env:
+        DGTP_TESTS_INTEGRATION_CONNECTION: ${{ secrets.DGTP_TESTS_INTEGRATION_CONNECTION }}
+      run: dotnet test /p:CollectCoverage=true --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Windows Tests            
+        path: tests/**/test-results.trx
+        reporter: dotnet-trx
 
   release:
     name: Semantic Release
     if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
     runs-on: ubuntu-latest
     needs:
-      - build
+      - build-linux
+      - build-windows
     steps:
       - name: Checkout
         uses: actions/checkout@v3
