build: try fix qoodana

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -2,9 +2,9 @@ name: Check DGTP
 
 on:
   push:
-    branches: [ "beta" ]
+    branches: ["beta"]
   pull_request:
-    branches: [ "main", "beta" ]
+    branches: ["main", "beta"]
 
 jobs:
   check:
@@ -20,57 +20,57 @@ jobs:
       checks: write
       pull-requests: write
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: 10.0.x
-        cache: true
-        cache-dependency-path: '**/packages.lock.json'
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: 10.0.x
+          cache: true
+          cache-dependency-path: "**/packages.lock.json"
 
-    - name: Restore dependencies
-      run: dotnet restore --locked-mode
+      - name: Restore dependencies
+        run: dotnet restore --locked-mode
 
-    - name: Build
-      run: dotnet build --no-restore
+      - name: Build
+        run: dotnet build --no-restore
 
-    - name: Run Tests
-      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --settings tests/coverlet.runsettings --blame-hang-timeout 3m
+      - name: Run Tests
+        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --settings tests/coverlet.runsettings --blame-hang-timeout 3m
 
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: ${{ matrix.os }} Tests
-        path: tests/**/test-results.trx
-        reporter: dotnet-trx
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: ${{ matrix.os }} Tests
+          path: tests/**/test-results.trx
+          reporter: dotnet-trx
 
-    - name: ReportGenerator
-      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.19
-      if: matrix.os == 'ubuntu-latest'
-      with:
-        reports: 'tests/**/coverage.cobertura.xml'
-        targetdir: 'coveragereport'
-        reporttypes: 'lcov'
+      - name: ReportGenerator
+        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.1
+        if: matrix.os == 'ubuntu-latest'
+        with:
+          reports: "tests/**/coverage.cobertura.xml"
+          targetdir: ".qodana/code-coverage"
+          reporttypes: "lcov"
 
-    - name: Archive coverage data
-      uses: actions/upload-artifact@v4
-      if: matrix.os == 'ubuntu-latest'
-      with:
-        name: net-coverage-data
-        path: coveragereport/lcov.info
+      - name: Archive coverage data
+        uses: actions/upload-artifact@v4
+        if: matrix.os == 'ubuntu-latest'
+        with:
+          name: net-coverage-data
+          path: .qodana/code-coverage/lcov.info
 
-    - name: 'Qodana Scan'
-      uses: JetBrains/qodana-action@v2025.3
-      if: matrix.os == 'ubuntu-latest'
-      env:
-        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
-      with:
-        args: "-i,NET/coverlet,--linter,jetbrains/qodana-dotnet:latest"
-          # When pr-mode is set to true, Qodana analyzes only the files that have been changed
-        pr-mode: false
-        use-caches: true
-        post-pr-comment: true
-        use-annotations: true
-
+      - name: "Qodana Scan"
+        uses: JetBrains/qodana-action@v2025.3
+        if: matrix.os == 'ubuntu-latest'
+        env:
+          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
+        with:
+          args:
+            "-i,NET/coverlet,--linter,jetbrains/qodana-dotnet:latest"
+            # When pr-mode is set to true, Qodana analyzes only the files that have been changed
+          pr-mode: false
+          use-caches: true
+          post-pr-comment: true
+          use-annotations: true
